# Introdução ao Pandas

Introdução sobre manipulação e análise de dados utilizando **Pandas**.

## Instalalação e importação

Comando para instalar via **pip**:

```bash
pip install pandas
```

In [2]:
# Importando o pandas
import pandas as pd

## Criando um DataFrame

Um `DataFrame` organiza dados em linhas e colunas.

In [3]:
# As chaves do dicionário são os nomes das colunas, as listas são valores
dados = {
    "nome": ["Ana", "Bruno", "Carlos", "Daniela", "Eduardo", "Gustavo"],
    "idade": [22, 25, 21, 28, 24, 23],
    "curso": [
        "Python",
        "Python",
        "Machine Learning",
        "Python",
        "Machine Learning",
        "Machine Learning"
    ],
    "nota": [8.5, 7.0, 9.2, 6.5, 8.0, 9.0],
    "aprovado": [True, True, True, False, True, True]
}

data_frame = pd.DataFrame(dados)

data_frame

      nome  idade             curso  nota  aprovado
0      Ana     22            Python   8.5      True
1    Bruno     25            Python   7.0      True
2   Carlos     21  Machine Learning   9.2      True
3  Daniela     28            Python   6.5     False
4  Eduardo     24  Machine Learning   8.0      True
5  Gustavo     23  Machine Learning   9.0      True

In [4]:
# Carregando dados lendo arquivo
#data_frame = pd.read_csv('caminho_do_arquivo')

print(data_frame)

      nome  idade             curso  nota  aprovado
0      Ana     22            Python   8.5      True
1    Bruno     25            Python   7.0      True
2   Carlos     21  Machine Learning   9.2      True
3  Daniela     28            Python   6.5     False
4  Eduardo     24  Machine Learning   8.0      True
5  Gustavo     23  Machine Learning   9.0      True

### Estrutura do DataFrame

- **Colunas:** características dos dados, como nome, idade e nota.
- **Linhas:** cada registro, neste caso, cada aluno.
- **Índice:** identifica cada linha. Por padrão, começa em `0`.
- **DataFrame:** estrutura que reúne todas essas informações.

## Visualizando e conhecendo os dados

### Primeiros registros

In [5]:
# Busca os primeiros n registros (padrão 5)
data_frame.head()

      nome  idade             curso  nota  aprovado
0      Ana     22            Python   8.5      True
1    Bruno     25            Python   7.0      True
2   Carlos     21  Machine Learning   9.2      True
3  Daniela     28            Python   6.5     False
4  Eduardo     24  Machine Learning   8.0      True

In [6]:
# n = 3
data_frame.head(3)

     nome  idade             curso  nota  aprovado
0     Ana     22            Python   8.5      True
1   Bruno     25            Python   7.0      True
2  Carlos     21  Machine Learning   9.2      True

### Últimos registros

In [7]:
# Busca os últimos n registros (padrão 5)
data_frame.tail()

      nome  idade             curso  nota  aprovado
1    Bruno     25            Python   7.0      True
2   Carlos     21  Machine Learning   9.2      True
3  Daniela     28            Python   6.5     False
4  Eduardo     24  Machine Learning   8.0      True
5  Gustavo     23  Machine Learning   9.0      True

In [8]:
# n = 2
data_frame.tail(2)

      nome  idade             curso  nota  aprovado
4  Eduardo     24  Machine Learning   8.0      True
5  Gustavo     23  Machine Learning   9.0      True

### Dimensões

In [9]:
# Número de linhas e colunas
data_frame.shape

(6, 5)

### Nomes das colunas

In [10]:
# Lista com nomes das colunas
data_frame.columns

Index(['nome', 'idade', 'curso', 'nota', 'aprovado'], dtype='str')

### Tipos de dados

In [11]:
# Coluna e tipo de dado
data_frame.dtypes

nome            str
idade         int64
curso           str
nota        float64
aprovado       bool
dtype: object

### Informações da estrutura

In [12]:
# Informações gerais do DataFrame
data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   nome      6 non-null      str
 1   idade     6 non-null      int64
 2   curso     6 non-null      str
 3   nota      6 non-null      float64
 4   aprovado  6 non-null      bool
dtypes: bool(1), float64(1), int64(1), str(2)
memory usage: 330.0 bytes

### Estatísticas descritivas

In [13]:
# Realiza as estatísticas nas colunas numéricas
data_frame.describe()

           idade      nota
count   6.000000  6.000000
mean   23.833333  8.033333
std     2.483277  1.089342
min    21.000000  6.500000
25%    22.250000  7.250000
50%    23.500000  8.250000
75%    24.750000  8.875000
max    28.000000  9.200000

## Selecionando colunas

Uma das operações mais comuns é selecionar apenas os dados de interesse.

### Uma coluna

In [14]:
# Seleção pelo nome da coluna
data_frame["nome"]

0        Ana
1      Bruno
2     Carlos
3    Daniela
4    Eduardo
5    Gustavo
Name: nome, dtype: str

Uma única coluna retorna uma `Series`.

### Várias colunas

In [15]:
data_frame[["nome", "nota"]]

      nome  nota
0      Ana   8.5
1    Bruno   7.0
2   Carlos   9.2
3  Daniela   6.5
4  Eduardo   8.0
5  Gustavo   9.0

### Seleção por posição com `iloc`

In [16]:
# Índice funciona semelhante ao slice
data_frame.iloc[1:-1]

      nome  idade             curso  nota  aprovado
1    Bruno     25            Python   7.0      True
2   Carlos     21  Machine Learning   9.2      True
3  Daniela     28            Python   6.5     False
4  Eduardo     24  Machine Learning   8.0      True

In [17]:
# Segundo índice é referente às colunas
data_frame.iloc[:, 0]

0        Ana
1      Bruno
2     Carlos
3    Daniela
4    Eduardo
5    Gustavo
Name: nome, dtype: str

In [18]:
data_frame.iloc[:, 0:2]

      nome  idade
0      Ana     22
1    Bruno     25
2   Carlos     21
3  Daniela     28
4  Eduardo     24
5  Gustavo     23

## Filtrando registros

### Nota maior ou igual a 8

In [19]:
# Utiliza operação de comparação para filtrar os valores
data_frame[data_frame["nota"] >= 8]

      nome  idade             curso  nota  aprovado
0      Ana     22            Python   8.5      True
2   Carlos     21  Machine Learning   9.2      True
4  Eduardo     24  Machine Learning   8.0      True
5  Gustavo     23  Machine Learning   9.0      True

### Filtrando por texto

In [20]:
data_frame[data_frame["curso"] == "Python"]

      nome  idade   curso  nota  aprovado
0      Ana     22  Python   8.5      True
1    Bruno     25  Python   7.0      True
3  Daniela     28  Python   6.5     False

### Combinando condições

In [21]:
# Utiliza operadores lógicos para combinar condições
data_frame[
    (data_frame["curso"] == "Python") &
    (data_frame["nota"] >= 8)
]

  nome  idade   curso  nota  aprovado
0  Ana     22  Python   8.5      True

Operadores importantes:

| Operador | Significado |
|---|---|
| `==` | Igual |
| `!=` | Diferente |
| `>` | Maior |
| `<` | Menor |
| `>=` | Maior ou igual |
| `<=` | Menor ou igual |
| `&` | E |
| `\|` | Ou |
| `~` | Negação |

Ao combinar condições no Pandas, coloque cada condição entre parênteses.

### Selecionando com `loc`

In [22]:
# Primeiro índice é o filtro e as segundo as colulas desejadas
data_frame.loc[data_frame["nota"] >= 8, ["nome", "nota"]]

      nome  nota
0      Ana   8.5
2   Carlos   9.2
4  Eduardo   8.0
5  Gustavo   9.0

## Criando e alterando colunas

### Criando uma coluna booleana

In [23]:
# Criação de coluna é semelhante à criação de nova chave no dicionário
data_frame["situacao"] = data_frame["nota"] >= 7

data_frame

      nome  idade             curso  nota  aprovado  situacao
0      Ana     22            Python   8.5      True      True
1    Bruno     25            Python   7.0      True      True
2   Carlos     21  Machine Learning   9.2      True      True
3  Daniela     28            Python   6.5     False     False
4  Eduardo     24  Machine Learning   8.0      True      True
5  Gustavo     23  Machine Learning   9.0      True      True

### Criando uma coluna textual com `numpy.where`

In [24]:
import numpy as np

# Primeiro parâmetro é a condição, segundo a atribuição caso verdadeira e terceira caso falsa
data_frame["resultado"] = np.where(
    data_frame["nota"] >= 7,
    "Aprovado",
    "Reprovado"
)

data_frame

      nome  idade             curso  nota  aprovado  situacao  resultado
0      Ana     22            Python   8.5      True      True   Aprovado
1    Bruno     25            Python   7.0      True      True   Aprovado
2   Carlos     21  Machine Learning   9.2      True      True   Aprovado
3  Daniela     28            Python   6.5     False     False  Reprovado
4  Eduardo     24  Machine Learning   8.0      True      True   Aprovado
5  Gustavo     23  Machine Learning   9.0      True      True   Aprovado

### Alterando uma coluna

In [25]:
# Criando uma cópia para preservar o DataFrame original.
df_copia = data_frame.copy()

# Atribui a transformação para todos os valores da coluna selecionada
df_copia["nota"] = df_copia["nota"] + 0.5

df_copia

      nome  idade             curso  nota  aprovado  situacao  resultado
0      Ana     22            Python   9.0      True      True   Aprovado
1    Bruno     25            Python   7.5      True      True   Aprovado
2   Carlos     21  Machine Learning   9.7      True      True   Aprovado
3  Daniela     28            Python   7.0     False     False  Reprovado
4  Eduardo     24  Machine Learning   8.5      True      True   Aprovado
5  Gustavo     23  Machine Learning   9.5      True      True   Aprovado

### Removendo colunas

In [26]:
data_frame = data_frame.drop(columns=["situacao", "resultado"])

data_frame

      nome  idade             curso  nota  aprovado
0      Ana     22            Python   8.5      True
1    Bruno     25            Python   7.0      True
2   Carlos     21  Machine Learning   9.2      True
3  Daniela     28            Python   6.5     False
4  Eduardo     24  Machine Learning   8.0      True
5  Gustavo     23  Machine Learning   9.0      True

## Calculando estatísticas

In [27]:
print("Média:", data_frame["nota"].mean())
print("Maior nota:", data_frame["nota"].max())
print("Menor nota:", data_frame["nota"].min())
print("Soma:", data_frame["nota"].sum())
print("Mediana:", data_frame["nota"].median())
print("Quantidade de notas:", data_frame["nota"].count())

Média: 8.033333333333333
Maior nota: 9.2
Menor nota: 6.5
Soma: 48.2
Mediana: 8.25
Quantidade de notas: 6

## Agrupando dados

O `groupby()` permite analisar registros separados por categorias.

### Média das notas por curso

In [28]:
data_frame.groupby("curso")["nota"].mean()

curso
Machine Learning    8.733333
Python              7.333333
Name: nota, dtype: float64

### Quantidade de alunos por curso

In [29]:
data_frame.groupby("curso")["nome"].count()

curso
Machine Learning    3
Python              3
Name: nome, dtype: int64

In [30]:
data_frame["curso"].value_counts()

curso
Python              3
Machine Learning    3
Name: count, dtype: int64

### Várias estatísticas por grupo

In [31]:
data_frame.groupby("curso")["nota"].agg(
    ["count", "mean", "min", "max"]
)

                  count      mean  min  max
curso
Machine Learning      3  8.733333  8.0  9.2
Python                3  7.333333  6.5  8.5

### Resultado como DataFrame

In [32]:
media_por_curso = data_frame.groupby("curso", as_index=False)["nota"].mean()

media_por_curso

              curso      nota
0  Machine Learning  8.733333
1            Python  7.333333

## Ordenando dados

### Ordem crescente

In [33]:
# Informa nome da coluna
data_frame.sort_values("nota")

      nome  idade             curso  nota  aprovado
3  Daniela     28            Python   6.5     False
1    Bruno     25            Python   7.0      True
4  Eduardo     24  Machine Learning   8.0      True
0      Ana     22            Python   8.5      True
5  Gustavo     23  Machine Learning   9.0      True
2   Carlos     21  Machine Learning   9.2      True

### Ordem decrescente

In [34]:
# Define a forma de ordenar
df_ordenado = data_frame.sort_values("nota", ascending=False)

df_ordenado

      nome  idade             curso  nota  aprovado
2   Carlos     21  Machine Learning   9.2      True
5  Gustavo     23  Machine Learning   9.0      True
0      Ana     22            Python   8.5      True
4  Eduardo     24  Machine Learning   8.0      True
1    Bruno     25            Python   7.0      True
3  Daniela     28            Python   6.5     False

### Ordenando por várias colunas

In [35]:
df_ordenado = data_frame.sort_values(
    by=["curso", "nota"],
    ascending=[True, False]
)

df_ordenado

      nome  idade             curso  nota  aprovado
2   Carlos     21  Machine Learning   9.2      True
5  Gustavo     23  Machine Learning   9.0      True
4  Eduardo     24  Machine Learning   8.0      True
0      Ana     22            Python   8.5      True
1    Bruno     25            Python   7.0      True
3  Daniela     28            Python   6.5     False

### Ordenando e redefinindo o índice

In [36]:
df_ordenado = data_frame.sort_values("nota", ascending=False).reset_index(drop=True)

df_ordenado

      nome  idade             curso  nota  aprovado
0   Carlos     21  Machine Learning   9.2      True
1  Gustavo     23  Machine Learning   9.0      True
2      Ana     22            Python   8.5      True
3  Eduardo     24  Machine Learning   8.0      True
4    Bruno     25            Python   7.0      True
5  Daniela     28            Python   6.5     False

## Trabalhando com valores ausentes

Em dados reais, algumas informações podem estar ausentes. O Pandas utiliza, entre outras representações, `NaN` para esses valores.

In [37]:
df_nulos = data_frame.copy()
df_nulos.loc[2, "nota"] = None

df_nulos

      nome  idade             curso  nota  aprovado
0      Ana     22            Python   8.5      True
1    Bruno     25            Python   7.0      True
2   Carlos     21  Machine Learning   NaN      True
3  Daniela     28            Python   6.5     False
4  Eduardo     24  Machine Learning   8.0      True
5  Gustavo     23  Machine Learning   9.0      True

### Identificando valores ausentes

In [38]:
df_nulos.isna()

    nome  idade  curso   nota  aprovado
0  False  False  False  False     False
1  False  False  False  False     False
2  False  False  False   True     False
3  False  False  False  False     False
4  False  False  False  False     False
5  False  False  False  False     False

In [39]:
df_nulos.isna().sum()

nome        0
idade       0
curso       0
nota        1
aprovado    0
dtype: int64

### Removendo registros com valores ausentes

In [40]:
df_nulos.dropna()

      nome  idade             curso  nota  aprovado
0      Ana     22            Python   8.5      True
1    Bruno     25            Python   7.0      True
3  Daniela     28            Python   6.5     False
4  Eduardo     24  Machine Learning   8.0      True
5  Gustavo     23  Machine Learning   9.0      True

In [41]:
df_nulos.dropna(subset=["nota"])

      nome  idade             curso  nota  aprovado
0      Ana     22            Python   8.5      True
1    Bruno     25            Python   7.0      True
3  Daniela     28            Python   6.5     False
4  Eduardo     24  Machine Learning   8.0      True
5  Gustavo     23  Machine Learning   9.0      True

### Preenchendo valores ausentes

In [42]:
media = df_nulos["nota"].mean()

df_preenchido = df_nulos.copy()
df_preenchido["nota"] = df_preenchido["nota"].fillna(media)

df_preenchido

      nome  idade             curso  nota  aprovado
0      Ana     22            Python   8.5      True
1    Bruno     25            Python   7.0      True
2   Carlos     21  Machine Learning   7.8      True
3  Daniela     28            Python   6.5     False
4  Eduardo     24  Machine Learning   8.0      True
5  Gustavo     23  Machine Learning   9.0      True

A escolha entre remover e preencher dados ausentes depende do significado dos dados e do objetivo da análise.

### Salvando um DataFrame em CSV

In [43]:
#data_frame.to_csv("alunos_exportados.csv", index=False)